# Generated by Django 5.1 on 2024-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_post_post_liked_by_post_likes_delete_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
