# Generated by Django 5.1 on 2024-10-22 23:28

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
