# Generated by Django 5.1 on 2024-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
    ]
