# Generated by Django 5.1 on 2024-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_alter_post_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
