# Generated by Django 5.1 on 2024-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], null=True),
        ),
    ]
