# Generated by Django 5.1 on 2024-11-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_post_dislikes_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
